### ISSUE TITLE
Enhance File Detection and Extend Compatibility for module read-bioinfo-metadata

### ISSUE THREAD

**Issue by Daniel-VM** [BU-ISCIII/relecov-tools#253]
Refactor `read_bioinfo_metadata.py` to enhance the detection of target files (those generated during bioinformatics analysis) and expand its applicability to additional bioinformatics software and pipelines.

### Task list
- [X] Code review and refactoring.
- [X] Create a bioinfo configuration file containing all properties required for tools used in the software or pipeline.
- [X] Implement automatic identification of bioinformatic analysis output files.
- [X] Update the method to verify and validate required files in bioinformatics analysis input.
- [X] Generate a new progress log method and format. This prints a formatted table in stdout, displaying warnings, errors, and valid specifications encountered while parsing metadata (sample and field level).
- [X] Expand `read-bioinfo-metadata` functionality to parse results from current and upcoming bioinformatics tools. Ideally, this module should be capable of identifying relevant metadata (must be specified via config files) based on the specific tool used in the bioinformatic analysis. 
     - [X] Add method to handle and map metadata in standard format (csv,tsv...).
     - [X] Add strategy to handle and map metadata from pipeline-specific scenarios(formats, data structures).
     - [X] Create assets/pipeline_utils to allocate pipeline-specific Class and Functions.
     

- [x] Fix the mapping sample name in the method `include_data_from_mapping_stats`. An error occurs when there are no matches between the mapping stats samples and the submitting_lab_sample_id in `processed_metadata_lab.json` (#240).
